config/routes.rb
Rails.application.routes.draw do

  resources :sprints

  resources :stories

  resources :projects

  get 'account_activations/edit'

  get 'users/new'

  get 'static_pages/home'

  get 'static_pages/help'
  get 'static_pages/sign_up'

  match '/',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/sign_up', to: 'static_pages#sign_up', via: 'get'
  match '/stories/:id/update_status', to: 'stories#update_status', via: 'post'
  match '/stories/:id/update_status_sprint', to: 'stories#update_status_sprint', via: 'post'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :account_activations, only: [:edit]

  resources :microposts

  root  'static_pages#home'
  match '/signup',  to: 'users#new',    via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via:'delete'

  namespace :projects do
    resources :user_tests
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :stories, dependent: :destroy
  has_many :sprints, dependent: :destroy
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 30 }

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show

  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    #===== Way 1. We can start from Project model ====
    #@project = Project.new(project_params)
    #@project.user_id = current_user.id


    #===== Way 2. We can start from User model, current user =====
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    #project_params[:user_id] = current_user.id
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :user_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show

    @stories = @project.stories.paginate(page: params[:page])

    #@stories =  Story.find_by_project_id(@project.id)  #get storie by project_id


    @stories_in_backlog  = Story.where(project_id:  params[:id],backlog:true).order(position: :asc)
    @stories_in_sprint  = Story.where(project_id:  params[:id],backlog:false).order(position: :asc)



  end

  # GET /projects/new
  def new
    @project = Project.new
  end



  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    #===== Way 1. We can start from Project model ====
    #@project = Project.new(project_params)
    #@project.user_id = current_user.id


    #===== Way 2. We can start from User model, current user =====
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    #project_params[:user_id] = current_user.id
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>



    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.user_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<%= javascript_include_tag "front-end/front-end.js" %>

<%= javascript_include_tag "front-end/vinazen.js" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user_id %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %> |
<%= link_to 'List of stories', stories_path(project_id: @project.id) %>|
<%= link_to 'Add story', new_story_path(id: @project.id) %>|
<%= link_to 'List of sprint', sprints_path(project_id: @project.id) %>|

<!--
#or can write (:id => @project.id)
-->


<div class="col-md-8">
  <% if @project.stories.any? %>
      <h3>Stories (<%= @project.stories.count %>)</h3>
      <ol class="stories">
        <%= render @stories %>
      </ol>
      <%= will_paginate @stories %>
  <% end %>
</div>






<div style="display: none;" id="link">stories_id_story_update_status</div>

<div class="wrap_column">
  <span  class="title"> Project's backlog</span>
  <div class="column" id="project_backlog">


    <% @stories_in_backlog.each do |story_in_backlog| %>


        <div class="portlet" id="<%= story_in_backlog.id %>">
          <div class="portlet-content">
            <%= story_in_backlog.name  + " "+ story_in_backlog.position.to_s  %>
            <div id="image">abc</div>
            <div class="img"><img src="http://images4.fanpop.com/image/photos/22400000/Beautiful-Horse-horses-22410583-500-313.jpg" /></div>
          </div>
        </div>

    <% end %>


  </div>
</div>






<div class="wrap_column">
  <span  class="title"> Sprint's backlog</span>
  <div class="column" id="sprint_backlog">


    <% @stories_in_sprint.each do |story_in_sprint| %>


        <div class="portlet" id="<%= story_in_sprint.id %>">
          <div class="portlet-content">
            <%= story_in_sprint.name  + " "+ story_in_sprint.position.to_s  %>
            <div id="image">abc</div>
            <div class="img"><img src="http://images4.fanpop.com/image/photos/22400000/Beautiful-Horse-horses-22410583-500-313.jpg" /></div>
          </div>
        </div>

    <% end %>


  </div>
</div>






<div class="clear"></div>