config/routes.rb
Rails.application.routes.draw do

  resources :sprints

  resources :stories

  resources :projects

  get 'account_activations/edit'

  get 'users/new'

  get 'static_pages/home'

  get 'static_pages/help'
  get 'static_pages/sign_up'

  match '/',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/sign_up', to: 'static_pages#sign_up', via: 'get'
  match '/stories/:id/update_status', to: 'stories#update_status', via: 'post'
  match '/stories/:id/update_status_sprint', to: 'stories#update_status_sprint', via: 'post'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :account_activations, only: [:edit]

  resources :microposts

  root  'static_pages#home'
  match '/signup',  to: 'users#new',    via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via:'delete'

  namespace :projects do
    resources :user_tests
  end

end

app/models/story.rb
class Story < ActiveRecord::Base

  belongs_to :project
  belongs_to :sprint
  belongs_to :user
  validates :project_id, presence: true
  validates :sprint_id, presence: true
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy, :update_status, :update_status_sprint ]

  # GET /stories
  # GET /stories.json
  def index


    if params[:project_id]
      @stories = Story.where("project_id = ?", params[:project_id])
    else
      @stories = Story.all
    end


  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @project = Project.find(@story.project_id).name



  end




  # GET /stories/new
  def new
    @story = Story.new

    if params[:id]
        @story.project_id = params[:id]

        #get sprint of project

        @sprints  = Sprint.all

        @sprints  = Sprint.where(project_id:  params[:id])

        #@sprints  = Sprint.find(1).map {|c| [c.name, c.id] }

    end



  end

  # GET /stories/1/edit
  def edit
  end


  #GET  /stories/1/update_status/

  def update_status

    #render plain: @story.name

    @from  = params[:from].to_s
    @to    = params[:to].to_s
    @new_position  = params[:new_position].to_i


    if ( @from  .eql?  "project_backlog" ) &&  (@to .eql? "sprint_backlog")
      @story.backlog = false
      @story.story_status = 1
      puts "move from project to sprint"

    elsif (@from  .eql?  "sprint_backlog") && (@to .eql? "project_backlog")
      @story.backlog = true
      @story.story_status = 0
      puts "move from sprint to project"
    end

   @story.position = @new_position

   #check all other stories in same backlog or sprints and add position increase

    @stories_in_backlog  = Story.where(project_id:  @story.project_id,backlog:true).where('position >= ?',@new_position).order(position: :asc)
    @stories_in_sprint  = Story.where(project_id:  @story.project_id,backlog:false).where('position >= ?',@new_position).order(position: :asc)


    if @story.backlog

      @new_position_story_in_backlog = @new_position
      @stories_in_backlog.each do |story_in_backlog|

        @new_position_story_in_backlog += 1;
        story_in_backlog.position = @new_position_story_in_backlog
        story_in_backlog.save()

      end


    end


    if !@story.backlog

      @new_position_story_in_sprint = @new_position
      @stories_in_sprint.each do |story_in_sprint|
        @new_position_story_in_sprint += 1;
        story_in_sprint.position = @new_position_story_in_sprint
        story_in_sprint.save()

      end
    end




    %#

    @stories_in_backlog_less  = Story.where(project_id:  @story.project_id,backlog:true).where('position < ?',@new_position).order(position: :asc)
    @stories_in_sprint_less  = Story.where(project_id:  @story.project_id,backlog:false).where('position < ?',@new_position).order(position: :asc)

    if @story.backlog
      @new_position_story_in_backlog_less = @new_position

      @stories_in_backlog_less.each do |story_in_backlog|

        @new_position_story_in_backlog_less -= 1;
        story_in_backlog.position = @new_position_story_in_backlog_less
        story_in_backlog.save()

      end

    end

    if !@story.backlog
      @new_position_story_in_sprint_less = @new_position
      @stories_in_sprint_less.each do |story_in_sprint|
        @new_position_story_in_sprint_less -= 1;
        story_in_sprint.position = @new_position_story_in_sprint_less


        story_in_sprint.save()

      end
    end


    #

    @story.save

  end



  #GET  /stories/1/update_status_in_sprint/

  def update_status_sprint

    @from  = params[:from].to_s
    @to    = params[:to].to_s
    @new_position  = params[:new_position].to_i


    if ( @to .eql? "sprint")
      @story.story_status = 0
      puts "move from project to sprint"


    elsif ( @to .eql? "sprint_backlog")
        @story.story_status = 1
        puts "move from project to sprint"

    elsif (@to .eql? "in_progress")
      @story.story_status = 2

    elsif (@to .eql? "sprint_done")
       @story.story_status = 3
    end

    @story.position = @new_position
    @story.save

  end


  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)



    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])

    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:name, :description, :backlog, :sprint_id, :project_id, :input, :output, :ratting, :position)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :backlog %><br>
    <%= f.check_box :backlog %>
  </div>

  <div class="field">
      <%= f.label :position  %><br>
      <%= f.text_field :position %>
  </div>




    <%= f.hidden_field :sprint_id, value: @story.sprint_id %>
    <%= f.collection_select :sprint_id, Sprint.all, :id, :name, :prompt => true %>



    <div class="field">
    <%= f.label :input %><br>
    <%= f.text_field :input %>
  </div>
  <div class="field">
    <%= f.label :output %><br>
    <%= f.text_field :output %>
  </div>
  <div class="field">
    <%= f.label :ratting %><br>
    <%= f.number_field :ratting %>
  </div>

 <%= f.hidden_field :project_id, value: @story.project_id %>
 <%= f.collection_select :project_id, Project.all, :id, :name, :prompt => true %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/_story.html.erb
  <li id="micropost-<%= story.id %>">
    <span><%= story.name %></span>
    <span><%= story.description %></span>
    <span><%= story.backlog %></span>
    <span><%= story.sprint  %></span>
    <span><%= story.project %></span>
    <span><%= story.input %></span>
    <span><%= story.output %></span>
    <span><%= story.ratting %></span>


    <span><%= link_to 'Show', story %></span>
    <span><%= link_to 'Edit', edit_story_path(story) %></span>
    <span><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></span>
  </li>

<br>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Backlog</th>
      <th>Sprint</th>
      <th>Projects</th>
      <th>Input</th>
      <th>Ouput</th>
      <th>Ratting</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.name %></td>
        <td><%= story.description %></td>
        <td><%= story.backlog %></td>


        <td><%= story.input %></td>

        <td><%= story.ratting %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @story.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @story.description %>
</p>

<p>
  <strong>Backlog:</strong>
  <%= @story.backlog %>
</p>



<p>
  <strong>Projects:</strong>
  <%= @story.project %>
</p>

<p>
  <strong>Sprint:</strong>
  <%= @story.sprint %>
</p>

<p>
  <strong>Input:</strong>
  <%= @story.input %>
</p>

<p>
  <strong>Output:</strong>
  <%= @story.output %>
</p>

<p>
  <strong>Ratting:</strong>
  <%= @story.ratting %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>